version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.0.3             #https://github.com/CircleCI-Public/aws-eks-orb/releases/tag/patch-release-v1.0.3
  kubernetes: circleci/kubernetes@1.2.0      

executors:
  python:
    docker:
      - image: circleci/python:3.7.3-stretch
  aws:
    docker:
      - image: amazon/aws-cli

jobs:
  linter:
    executor: python
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            sudo chmod +x /bin/hadolint
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint    
  
  build-and-push-docker-image:
    working_directory: ~/apps
    docker:
      - image: docker:20.10.21-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build/Push docker image
          command: |
            docker login --username rbtadikonda --password $DOCKER_HUB_PASSWORD
            docker build --tag=rbtdevopscapstone .
            docker tag rbtdevopscapstone rbtadikonda/rbtdevopscapstone
            docker push rbtadikonda/rbtdevopscapstone

  create-eks-cluster:
      executor: aws-eks/python
      parameters:
        eks-cluster-name:
          description: |
            EKS cluster name
          type: string
      steps:
        - checkout
        - aws-eks/install-aws-iam-authenticator
             
        - run:
            name: install eksctl
            command: |
              if command -v eksctl1 > /dev/null
                then
                  echo "eksctl is already available"
                  exit 0
              fi 
              mkdir -p temp
              curl -sL "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C temp
              chmod +x temp/eksctl
              sudo mv temp/eksctl /usr/local/bin/
              rm -Rf temp
        - aws-eks/create-cluster:
            cluster-name: << parameters.eks-cluster-name >>
            zones: us-east-1a,us-east-1b,us-east-1c,us-east-1d,us-east-1f
            node-type: t2.micro
            nodes-max: 4

  deploy-to-eks-cluster:
    executor: aws-eks/python
    parameters:
      eks-cluster-name:
        description: |
          deployment to eks cluster
        type: string
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.eks-cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: false
          resource-file-path: eks-deployment/deployment-service.yml
          resource-name: deployment/rbtdevopscapstone

  check-cluster:
    executor: aws-eks/python
    parameters:
      eks-cluster-name:
        description: |
          Checking Cluster
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.eks-cluster-name >>
      - run:
          name: check cluster for services deployemnt and nodes
          command: |
            kubectl get services
            kubectl get deployment
            kubectl get nodes
            kubectl get pods -n rbt-devops-capstone

workflows:
  default:
    jobs:
      - linter
      - build-and-push-docker-image:
          requires:
            - linter
      - create-eks-cluster:
          eks-cluster-name: rbt-devops-capstone
          requires:
            - build-and-push-docker-image
      - deploy-to-eks-cluster:
          eks-cluster-name: rbt-devops-capstone
          requires: 
            - create-eks-cluster
      - aws-eks/update-container-image:
          cluster-name: rbt-devops-capstone
          container-image-updates: rbtdevopscapstone=rbtadikonda/rbtdevopscapstone
          record: true
          resource-name: deployment/rbtdevopscapstone
          requires: 
            - deploy-to-eks-cluster
      - check-cluster:
          eks-cluster-name: rbt-devops-capstone
          requires: 
            - aws-eks/update-container-image